### PR TITLE
Fix YNAB budget when there is only one budget id

### PR DESCRIPTION
**Pull request by baruchiro**
Copy of #585 but for #579

### CODE REVIEW

**Comment by brafdlog** [comment]
Hey
Thanks for the PR!
Regarding the formatting, when there are formatting changes like this, please do them in a separate commit, as it makes it hard to see what are the actual changes you want vs just formatting.
Also, why are you changing the formatting?

**Comment by brafdlog** [comment]
I made a related fix here: https://github.com/brafdlog/caspion/commit/b6471362d9cfd91c3e8b515547c55dd7ecd98cad
Not sure why I don't see it in the code

**Comment by baruchiro** [comment]
@brafdlog I made a mistake in this PR. I created a PR from one branch into two target branches: `master` and `vite-electron-builder`. Now we need to merge the `vite-electron-builder` into the PR branch.

And this is why you can't see your change, because there is a conflict.

But your code is there. If it solves the problem, please close this PR.

**Comment by brafdlog** [comment]
@shaiu  if you take a build from [brafdlog:vite-electron-builder](https://github.com/brafdlog/caspion/tree/vite-electron-builder) so you still experience the bug?

**Comment by brafdlog** [comment]
> @brafdlog I made a mistake in this PR. I created a PR from one branch into two target branches: `master` and `vite-electron-builder`. Now we need to merge the `vite-electron-builder` into the PR branch.
> 
> And this is why you can't see your change, because there is a conflict.
> 
> But your code is there. If it solves the problem, please close this PR.

Just saw this.
It should solve the bug, @shaiu  if it doesn't feel free to reopen

**Pull request closed without merging**
