### PR TITLE
upgrade israeli-bank-scrapers to v1.14.1

### PR DESCRIPTION
**Pull request by baruchiro**
https://github.com/eshaham/israeli-bank-scrapers/compare/v1.13.5...v1.14.3

### CODE REVIEW

**Comment by baruchiro** [comment]
@brafdlog or anyone, we need to test this, they upgraded the Puppeteer version and I want to be sure it is not broken.

**Comment by brafdlog** [comment]
@baruchiro I checked and visa cal doesn't work because of [this issue](https://github.com/eshaham/israeli-bank-scrapers/issues/696) that was fixed in version 1.14.3.
Can you update to version 1.14.3? Then I will check again.
I can't run the dev environment with the mac.

**Comment by baruchiro** [comment]
@brafdlog I forgot this PR.
Yes, I upgraded the version to `v1.14.3`, I also can't use my Mac and need to test it on my wife's computer.

**Comment by brafdlog** [comment]
@baruchiro its working

**Pull request merged**
