### PR TITLE
Fix: blank screen after 2.0.5

### PR DESCRIPTION
**Pull request by shaiu**
This fixes the issue in 2.0.5 when loading the app there is a blank screen (no importers and exporters)

Added a default config to ConfigStore constructor

### CODE REVIEW

**Comment by baruchiro** [comment]
I think it will be fixed by #601, if not, I will merge yours.

**Comment by shaiu** [comment]
> I think it will be fixed by #601, if not, I will merge yours.

How exactly? I think I introduced a major bug in 2.0.5 that erases users config..
So this should be merged and also we should remove 2.0.5 from Releases

**Comment by baruchiro** [comment]
> > I think it will be fixed by #601, if not, I will merge yours.
> 
> How exactly? I think I introduced a major bug in 2.0.5 that erases users config.. So this should be merged and also we should remove 2.0.5 from Releases

Do you think it is a bug introduced in 2.0.5?
If so, we didn't find it, we just covered it, and it may return. You and my solutions both fall back to the default config (in my fix I'm doing it right after reading the config, if it is an empty object...). If the bug is still there, users may be reset to the default config without warning.

Anyway, I pushed my fix, and if the bug is still there, we will see it happen and find it.

**Comment by baruchiro** [comment]
@shaiu why did you open it again?

I think it can be closed.

**Comment by shaiu** [comment]
@baruchiro 
I believe that this is the bug:
config: Config = {} as Config;

**Comment by baruchiro** [comment]
Oh, I see it now.

But I prefer you don't create a default config here. We already have the default config on the 'main'/'backend' side, and the `saveConfigIntoFile` will not save it if it is `undefined`. Then, it will try to load it from the backend, and if it is empty or does not exist on the filesystem, the backend will return the default config.

**Pull request merged**
